### ISSUE TITLE
Auto

### ISSUE THREAD

**Issue by TCMBoby** [kava-i/Gawasi-Gukum#10]
Tims Auto abklären

**Comment by georgbuechner** [comment]
Also aktuell ist der Stand für die Hinfahrt;
- 14:00 Treffen zum einladen bei Jan (Alex, Jan)
- 16:00 Losfahren in Frankfurt (Fahrer: Vater von Anna - Helmut)
- 17:00 Treffen in Neu-Anspach
Rückfahrt: ich habe meine Eltern gefragt, ob sie uns fahren. Habe allerdings noch keine Antwort.

**Comment by georgbuechner** [comment]
Meine Eltern fahren am Sonntag einmal nach Frankfurt
