### ISSUE TITLE
Securitys über Ankunftszeit kommunizieren

### ISSUE THREAD

**Issue by georgbuechner** [kava-i/Gawasi-Gukum#13]
Die Securitys müssen informiert werden, dass sie um 15:00 schon vor Ort sein müssen. 
Frage: 
- reicht Twitter?
- oder sollten wir sie über sms/ email informieren?

**Comment by alleonhardt** [comment]
Sollten das nicht eigentlich die Verhoerer machen? Und dann via Twitter? SMS wuerde ich nicht machen viele haben die SMS vermutlich nicht eingelegt. Email waere vermutlich die sicherste Variante.

**Comment by georgbuechner** [comment]
Mail an alle Teilnehmer ist raus. Einzelnd an Secus mit Bahnfahrzeiten
