### ISSUE TITLE
SIM Karte

### ISSUE THREAD

**Issue by TCMBoby** [kava-i/Gawasi-Gukum#8]
Sim Karte für Tom Schwarz. Muss in Brief verpackt werden. @ShadowItaly hast du noch den Brief?

**Comment by georgbuechner** [comment]
Ich informiere mich gerade bei Congstart und versuche eine neue SimKarte zu bekommen mit der gleichen Nummer.

**Comment by georgbuechner** [comment]
Also sim-karte ist in 2-3 Werktagen bei mir zu hause. Dann müssen wir keinen neuen Twitter erstellen etc. Ist besser so, dachte ich mir...
